version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serverless
    versions:
    - 2.28.1
    - 2.28.3
    - 2.28.6
    - 2.28.7
    - 2.29.0
    - 2.30.2
    - 2.30.3
    - 2.31.0
    - 2.32.0
    - 2.32.1
    - 2.33.1
    - 2.34.0
    - 2.35.0
    - 2.37.1
    - 2.37.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
