service: hello-world-typescript
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
       - http:
          path: greet
          method: get
          
plugins:
  - serverless-plugin-typescript
  - serverless-offline